name: gamepads_windows
description: Windows implementation of gamepads, a Flutter plugin to handle gamepad input across multiple platforms.
version: 0.1.0
homepage: https://github.com/flame-engine/gamepads
repository: https://github.com/flame-engine/gamepads/tree/master/packages/gamepads_windows

flutter:
  plugin:
    implements: gamepads
    platforms:
      windows:
        pluginClass: GamepadsWindowsPluginCApi

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  gamepads_platform_interface: ^0.1.0

dev_dependencies:
  flame_lint: ^0.2.0
  flutter_test:
    sdk: flutter