name: gamepads_windows
resolution: workspace
description: Windows implementation of gamepads, a Flutter plugin to handle gamepad input across multiple platforms.
version: 0.1.4+1
homepage: https://github.com/flame-engine/gamepads
repository: https://github.com/flame-engine/gamepads/tree/main/packages/gamepads_windows

flutter:
  plugin:
    implements: gamepads
    platforms:
      windows:
        pluginClass: GamepadsWindowsPluginCApi

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  gamepads_platform_interface: ^0.1.2+1

dev_dependencies:
  flame_lint: ^1.4.1
  flutter_test:
    sdk: flutter
